language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew uninstall xctool
  - brew install xctool --HEAD
script:
  - xctool -project ios-app-bootstrap.xcodeproj -sdk iphonesimulator -scheme ios-app-bootstrap build test
