osx_image: xcode9
language: objective-c
cache: cocoapods
before_install:
  - brew update
  - rvm use $RVM_RUBY_VERSION
install:
  - bundle install --without=documentation --path ../travis_bundle_dir
script:
  - echo hi
